<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'FacebookModule\Module'                        => __DIR__ . '/Module.php',
    'FacebookModule\Controller\IndexController' => __DIR__ . '/src/FacebookModule/Controller/IndexController.php',
    'FacebookModuleTest\Framework\TestCase'        => __DIR__ . '/tests/FacebookModule/Framework/TestCase.php',
    'FacebookModuleTest\SampleTest'                => __DIR__ . '/tests/FacebookModule/SampleTest.php',
);
